baseURL = "https://seobaeksol.github.io/"
title = "Seobaeksol Dev Blog"
theme = "PaperMod"
enableRobotsTXT = true
buildDrafts = false
defaultContentLanguage = "ko"
defaultContentLanguageInSubdir = true
hasCJKLanguage = true

[languages]

[languages.ko]
languageName = "한국어"
weight = 1
contentDir = "content/ko"
title = "Seobaeksol 블로그"

[languages.en]
languageName = "English"
weight = 2
contentDir = "content/en"
title = "Seobaeksol Blog"

[languages.ko.menu]
[[languages.ko.menu.main]]
name = "홈"
url = "/"
weight = 1

[[languages.ko.menu.main]]
name = "포스트"
url = "/posts/"
weight = 2

[[languages.ko.menu.main]]
name = "일기"
url = "/diary/"
weight = 3


[languages.en.menu]
[[languages.en.menu.main]]
name = "Home"
url = "/"
weight = 1

[[languages.en.menu.main]]
name = "Posts"
url = "/posts/"
weight = 2

[[languages.en.menu.main]]
name = "Diary"
url = "/diary/"
weight = 3


[pagination]
pagerSize = 10

[params]
env = "production"
defaultTheme = "auto"
ShowReadingTime = true
ShowCodeCopyButtons = true
ShowPostNavLinks = true
ShowToc = true

[outputs]
home = ["HTML", "RSS", "JSON"]

[params.assets]
customCSS = ["custom.css", "css/extended/fonts.css"]
