baseURL = "https://seobaeksol.github.io/"
title = "Seobaeksol Dev Blog"
theme = "PaperMod"
enableRobotsTXT = true
buildDrafts = false
defaultContentLanguage = "ko"
defaultContentLanguageInSubdir = false
hasCJKLanguage = true

[outputs]
home = ["HTML", "RSS", "JSON"]

[languages]

[languages.ko]
languageName = "한국어"
weight = 1
title = "Seobaeksol 블로그"

[languages.en]
languageName = "English"
weight = 2
title = "Seobaeksol Blog"

[languages.ko.menu]
[[languages.ko.menu.main]]
name = "홈"
url = "/"
weight = 1

[[languages.ko.menu.main]]
name = "포스트"
url = "/posts/"
weight = 2

[[languages.ko.menu.main]]
name = "일기"
url = "/diary/"
weight = 3

[[languages.ko.menu.main]]
name = "검색"
url = "/search/"
weight = 4


[languages.en.menu]
[[languages.en.menu.main]]
name = "Home"
url = "/"
weight = 1

[[languages.en.menu.main]]
name = "Posts"
url = "/posts/"
weight = 2

[[languages.en.menu.main]]
name = "Diary"
url = "/diary/"
weight = 3

[[languages.en.menu.main]]
name = "Search"
url = "/search/"
weight = 4


[pagination]
pagerSize = 10

[params]
env = "production"
defaultTheme = "auto"
ShowReadingTime = true
ShowCodeCopyButtons = true
ShowPostNavLinks = true
ShowToc = true
ShowSearch = true
ShowShareButtons = true
ShowBreadCrumbs = true
comments = true

[params.homeInfoParams]
Title = "Seobaeksol Dev Blog"
Content = "Seobaeksol Dev Blog"

[[params.socialIcons]]
name = "github"
url = "https://github.com/seobaeksol"

[params.assets]
customCSS = ["custom.css", "css/extended/fonts.css"]
